config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :horses
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/index', to: 'home#index', as: 'index'

  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/horse.rb
class Horse < ApplicationRecord
    has_one_attached :cover
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end

end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :set_horse, only: %i[ show edit update destroy ]

  # GET /horses or /horses.json
  def index
    @horses = Horse.all
  end

  # GET /horses/1 or /horses/1.json
  def show
  end

  # GET /horses/new
  def new
    @horse = Horse.new
  end

  # GET /horses/1/edit
  def edit
  end

  # POST /horses or /horses.json
  def create
    @horse = Horse.new(horse_params)

    respond_to do |format|
      if @horse.save
        format.html { redirect_to @horse, notice: "Horse was successfully created." }
        format.json { render :show, status: :created, location: @horse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horses/1 or /horses/1.json
  def update
    respond_to do |format|
      if @horse.update(horse_params)
        format.html { redirect_to @horse, notice: "Horse was successfully updated." }
        format.json { render :show, status: :ok, location: @horse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horses/1 or /horses/1.json
  def destroy
    @horse.destroy
    respond_to do |format|
      format.html { redirect_to horses_url, notice: "Horse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horse
      @horse = Horse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def horse_params
      params.require(:horse).permit(:nome, :descrizione, :eta, :cover)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:cognome, :nome, :email, :numero, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<br>
<div class="container">
    <div class="card bg-dark text-white">
        <img src="/images/1c.jpg.png" class="card-img" alt="500px">
        <div class="card-img-overlay">
            <h2 class="card-title">Cavalli</h5>
            <h4 class="card-text">Scegli fra i nostri fantastici cavalli.</p>
            <br>
            <a href="/horses"><button type="button" class="btn btn-primary">Cavalli</button></a>
        </div>
    </div>
</div>

<br>

<div class="container">
    <div class="card bg-dark text-white">
        <img src="/images/2c.png" class="card-img" alt="500px">
        <div class="card-img-overlay">
            <h2 class="card-title">Newsletter</h5>
            <h4 class="card-text">Iscriviti alla newsletter</p>
            <br>
            <a href="/users/new"><button type="button" class="btn btn-primary">Iscriviti</button></a>
            <br>
        </div>
    </div>
</div>

<br>

app/views/horses/_form.html.erb
<%= form_with(model: horse) do |form| %>
  <% if horse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
        <% horse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="container-fluid">
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :nome, class: 'form-label'%>
          <%= form.text_field :nome, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :descrizione, class: 'form-label'%>
          <%= form.text_field :descrizione, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :eta, class: 'form-label' %>
          <%= form.number_field :eta, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm form-label">
          <%= form.label :cover, class: 'form-label' %>
          <%= form.file_field :cover, class: 'form-control' %>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Aggiungi/modifica cavallo', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/horses/edit.html.erb
<h1>Modifica cavallo</h1>

<%= render 'form', horse: @horse %>
<br>
<%= link_to 'Mostra', @horse, class:'btn btn-primary' %> |
<%= link_to 'Indietro', horses_path, class:'btn btn-primary' %>

app/views/horses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cavalli</h1>


<div class="container">
  <div class="row">
    <% @horses.each do |horse| %>
    <div class="col">
        <div class="card" style="width: 18rem;">
          <% if horse.cover.attached? %>
              <%= link_to (image_tag url_for(horse.cover),class: 'card-img-top'), horse %>
          <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= horse.nome %>, <%= horse.eta %> anni</h5>
          <p class="card-text"><%= horse.descrizione %></p>
          <%= link_to 'Modifica', edit_horse_path(horse), class:'btn btn-primary' %>
          <%= link_to 'Elimina', horse, method: :delete, data: { confirm: 'Sei sicuro?' }, class:'btn btn-danger' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'Nuovo cavallo', new_horse_path, class: 'btn btn-primary' %>

app/views/horses/new.html.erb
<h1>Nuovo cavallo</h1>

<%= render 'form', horse: @horse %>

<br>
<%= link_to 'Indietro', horses_path, class:'btn btn-primary' %>

app/views/horses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <% if @horse.cover.attached? %>
  <%= image_tag url_for(@horse.cover)%>
  <% end %>
</p>

<p>
  <strong><%= @horse.nome %>, <%= @horse.eta %> anni</strong>
</p>

<p>
  <strong><%= @horse.descrizione %></strong>
</p>


<%= link_to 'Modifica', edit_horse_path(@horse), class: 'btn btn-primary' %> |
<%= link_to 'Indietro', horses_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="assets/css/style.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/index">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/horses">Cavalli</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/horses/new">Nuovo Cavallo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/users/new">Newsletter</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <%= yield %>
    
<br>
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Cavalli</h3>
                        <ul>
                            <li><a href="/horses">Guarda cavalli</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Newsletter</h3>
                        <ul>
                            <li><a href="/users/new">iscriviti alla newsletter</a></li>
                        </ul>
                    </div>
                  
                    <div class="col-md-6 item text">
                        <h3>Maneggio da Erty</h3>
                        <p>Da tante generazioni ci prendiamo cura dei migliori cavalli.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Maneggio da Erty © 1969</p>
            </div>
        </footer>
    </div>
  </body>
</html>



    

    
    

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :cognome, class: 'form-label'%>
        <%= form.text_field :cognome, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :nome, class: 'form-label'%>
        <%= form.text_field :nome, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :email, class: 'form-label'%>
        <%= form.text_field :email, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :numero, class: 'form-label' %>
        <%= form.number_field :numero, class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm form-label">
        <%= form.label :note, class: 'form-label' %>
        <%= form.text_field :note, class: 'form-control' %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Crea/modifica utente', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Modifica utente</h1>

<%= render 'form', user: @user %>

<%= link_to 'Mostra', @user, class:'btn btn-primary' %> |
<%= link_to 'Indietro', users_path, class:'btn btn-primary' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Cognome</th>
      <th scope="col">Nome</th>
      <th scope="col">Email</th>
      <th scope="col">Numero</th>
      <th scope="col">Note</th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %> 
    <tr>
    
      <td><%= user.cognome %></td>
    
      <td><%= user.nome %></td>

      <td><%= user.email %> </td>
      
      <td><%= user.numero %> €</td>

      <td><%= user.note %> </td>
    
      <td><%= link_to 'Modifica', edit_user_path(user), class: 'btn btn-primary' %></td>  
    
      <td><%= link_to 'Elimina', user, method: :delete, data: { confirm: 'Sei sicuro?' }, class: 'btn btn-danger' %></td>  

      </tr>
    <% end %>  
  </tbody>
</table>

<br>

<%= link_to 'Nuovo utente', new_user_path, class: 'btn btn-primary'%>

app/views/users/new.html.erb
<h1>Nuovo utente</h1>

<%= render 'form', user: @user %>

<br>
<%= link_to 'Indietro', users_path, class:'btn btn-primary' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cognome:</strong>
  <%= @user.cognome %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @user.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @user.numero %>
</p>

<p>
  <strong>Note:</strong>
  <%= @user.note %>
</p>

<%= link_to 'Mostra', edit_user_path(@user), class:'btn btn-primary' %> |
<%= link_to 'Indietro', users_path, class:'btn btn-primary' %>